config {
  type: "operations",
  dependencies: ["silver_pos_transactions"]
}

UPDATE ${ref("dim_store")} D
SET
    effective_to = CURRENT_TIMESTAMP(),
    is_current = FALSE
WHERE D.is_current = TRUE
AND EXISTS (

    WITH latest_store AS (

        SELECT *
        FROM (

            SELECT
                store_id,
                store_name,
                store_city,
                store_state,
                region,
                store_type,

                ROW_NUMBER() OVER (
                    PARTITION BY store_id
                    ORDER BY transaction_date DESC
                ) rn

            FROM ${ref("silver_pos_transactions")}
        )
        WHERE rn = 1
    )

    SELECT 1
    FROM latest_store S
    WHERE S.store_id = D.store_id
    AND (
        D.store_name IS DISTINCT FROM S.store_name
        OR D.store_city IS DISTINCT FROM S.store_city
        OR D.store_state IS DISTINCT FROM S.store_state
        OR D.region IS DISTINCT FROM S.region
        OR D.store_type IS DISTINCT FROM S.store_type
    )
);