config {
  type: "operations",
  dependencies: ["expire_store_records"]
}

INSERT INTO ${ref("dim_store")}
(
    store_sk,
    store_id,
    store_name,
    store_city,
    store_state,
    region,
    store_type,
    effective_from,
    effective_to,
    is_current
)

WITH latest_store AS (

    SELECT *
    FROM (

        SELECT
            store_id,
            store_name,
            store_city,
            store_state,
            region,
            store_type,

            ROW_NUMBER() OVER (
                PARTITION BY store_id
                ORDER BY transaction_date DESC
            ) rn

        FROM ${ref("silver_pos_transactions")}
    )
    WHERE rn = 1
),

records_to_insert AS (

    SELECT S.*
    FROM latest_store S

    LEFT JOIN ${ref("dim_store")} D
        ON S.store_id = D.store_id
       AND D.is_current = TRUE

    WHERE D.store_id IS NULL

       OR D.store_name IS DISTINCT FROM S.store_name
       OR D.store_city IS DISTINCT FROM S.store_city
       OR D.store_state IS DISTINCT FROM S.store_state
       OR D.region IS DISTINCT FROM S.region
       OR D.store_type IS DISTINCT FROM S.store_type
)

SELECT
    (
        COALESCE(
            (SELECT MAX(store_sk) FROM ${ref("dim_store")}),
            0
        )
        +
        ROW_NUMBER() OVER (ORDER BY store_id)
    ) AS store_sk,

    store_id,
    store_name,
    store_city,
    store_state,
    region,
    store_type,

    CURRENT_TIMESTAMP(),
    TIMESTAMP('9999-12-31'),
    TRUE

FROM records_to_insert;