config {
  type: "incremental",
  schema: "retail_silver",
  uniqueKey: ["transaction_id","product_id"]
}

SELECT
    transaction_id,
    transaction_date,
    store_id,
    store_name,
    store_city,
    store_state,
    region,
    store_type,
    product_id,
    product_name,
    category,
    sub_category,
    xyz,
    brand,
    unit_price,
    cost_price,
    customer_id,
    customer_name,
    customer_email,
    customer_city,
    customer_state,
    membership_tier,
    registration_date,
    quantity_sold,
    discount_applied,
    final_amount
FROM ${ref("raw_pos_transactions_incremental")}