config {
  type: "operations",
  dependencies: ["silver_pos_transactions"]
}

UPDATE ${ref("dim_product")} D
SET
    effective_to = CURRENT_TIMESTAMP(),
    is_current = FALSE
WHERE D.is_current = TRUE
AND EXISTS (

    WITH latest_product AS (

        SELECT *
        FROM (

            SELECT
                product_id,
                product_name,
                category,
                sub_category,
                brand,

                ROW_NUMBER() OVER (
                    PARTITION BY product_id
                    ORDER BY transaction_date DESC
                ) rn

            FROM ${ref("silver_pos_transactions")}
        )
        WHERE rn = 1
    )

    SELECT 1
    FROM latest_product S
    WHERE S.product_id = D.product_id
    AND (
        D.product_name IS DISTINCT FROM S.product_name
        OR D.category IS DISTINCT FROM S.category
        OR D.sub_category IS DISTINCT FROM S.sub_category
        OR D.brand IS DISTINCT FROM S.brand
    )
);