config {
  type: "operations",
  dependencies: ["expire_product_records"]
}

INSERT INTO ${ref("dim_product")}
(
    product_sk,
    product_id,
    product_name,
    category,
    sub_category,
    brand,
    effective_from,
    effective_to,
    is_current
)

WITH latest_product AS (

    SELECT *
    FROM (

        SELECT
            product_id,
            product_name,
            category,
            sub_category,
            brand,

            ROW_NUMBER() OVER (
                PARTITION BY product_id
                ORDER BY transaction_date DESC
            ) rn

        FROM ${ref("silver_pos_transactions")}
    )
    WHERE rn = 1
),

records_to_insert AS (

    SELECT S.*
    FROM latest_product S

    LEFT JOIN ${ref("dim_product")} D
        ON S.product_id = D.product_id
       AND D.is_current = TRUE

    WHERE D.product_id IS NULL

       OR D.product_name IS DISTINCT FROM S.product_name
       OR D.category IS DISTINCT FROM S.category
       OR D.sub_category IS DISTINCT FROM S.sub_category
       OR D.brand IS DISTINCT FROM S.brand
)

SELECT
    (
        COALESCE(
            (SELECT MAX(product_sk) FROM ${ref("dim_product")}),
            0
        )
        +
        ROW_NUMBER() OVER (ORDER BY product_id)
    ) AS product_sk,

    product_id,
    product_name,
    category,
    sub_category,
    brand,

    CURRENT_TIMESTAMP(),
    TIMESTAMP('9999-12-31'),
    TRUE

FROM records_to_insert;