config {
  type: "operations",
  dependencies: ["silver_pos_transactions"]
}

UPDATE ${ref("dim_customer")} D
SET
    effective_to = CURRENT_TIMESTAMP(),
    is_current = FALSE
WHERE D.is_current = TRUE
AND EXISTS (

    WITH latest_customer AS (

        SELECT *
        FROM (

            SELECT
                customer_id,
                customer_name,
                customer_email,
                customer_city,
                customer_state,
                membership_tier,
                registration_date,

                ROW_NUMBER() OVER (
                    PARTITION BY customer_id
                    ORDER BY transaction_date DESC
                ) rn

            FROM ${ref("silver_pos_transactions")}
        )
        WHERE rn = 1
    )

    SELECT 1
    FROM latest_customer S
    WHERE S.customer_id = D.customer_id
    AND (
        D.customer_name IS DISTINCT FROM S.customer_name
        OR D.customer_email IS DISTINCT FROM S.customer_email
        OR D.customer_city IS DISTINCT FROM S.customer_city
        OR D.customer_state IS DISTINCT FROM S.customer_state
        OR D.membership_tier IS DISTINCT FROM S.membership_tier
        OR D.registration_date IS DISTINCT FROM S.registration_date
    )
);