config {
  type: "operations",
  dependencies: ["expire_customer_records"]
}

INSERT INTO ${ref("dim_customer")}
(
    customer_sk,
    customer_id,
    customer_name,
    customer_email,
    customer_city,
    customer_state,
    membership_tier,
    registration_date,
    effective_from,
    effective_to,
    is_current
)

WITH latest_customer AS (

    SELECT *
    FROM (

        SELECT
            customer_id,
            customer_name,
            customer_email,
            customer_city,
            customer_state,
            membership_tier,
            registration_date,

            ROW_NUMBER() OVER (
                PARTITION BY customer_id
                ORDER BY transaction_date DESC
            ) rn

        FROM ${ref("silver_pos_transactions")}
    )
    WHERE rn = 1
),

records_to_insert AS (

    SELECT S.*
    FROM latest_customer S

    LEFT JOIN ${ref("dim_customer")} D
        ON S.customer_id = D.customer_id
       AND D.is_current = TRUE

    WHERE D.customer_id IS NULL

       OR D.customer_name IS DISTINCT FROM S.customer_name
       OR D.customer_email IS DISTINCT FROM S.customer_email
       OR D.customer_city IS DISTINCT FROM S.customer_city
       OR D.customer_state IS DISTINCT FROM S.customer_state
       OR D.membership_tier IS DISTINCT FROM S.membership_tier
       OR D.registration_date IS DISTINCT FROM S.registration_date
)

SELECT
    (
        COALESCE(
            (SELECT MAX(customer_sk) FROM ${ref("dim_customer")}),
            0
        )
        +
        ROW_NUMBER() OVER (ORDER BY customer_id)
    ) AS customer_sk,

    customer_id,
    customer_name,
    customer_email,
    customer_city,
    customer_state,
    membership_tier,
    registration_date,

    CURRENT_TIMESTAMP(),
    TIMESTAMP('9999-12-31'),
    TRUE

FROM records_to_insert;